### ISSUE TITLE
Clearing the details text text curser disapears

### ISSUE THREAD

**Issue by shoey** [akilli/ckeditor4-detail#1]
When editing the details title if you clear the details text using delete of use backspace to clear the text cursor disappears and then won't be able to add any text.

**Comment by akilli** [comment]
I guess with Chrome?

**Comment by shoey** [comment]
Yes although I haven’t tried any other browsers yet. I was experimenting and found if you look for the keycode for delete and backspace and if the value was an empty string you could set the editor to an empty string like you were with space but if it’s blank on the blur event it cause other issues.

**Comment by akilli** [comment]
The editable summary element was always a pain in the ass, especially with Chrome. In earlier versions I worked around that, but well, the result was ok, but not really what I wanted.

Firefox handles it exactly they way it is intended. It should be possible with Chrome too. I will look into it, when I got time. But feel free to fix it before ;-)

**Comment by akilli** [comment]
Today I had a little bit of time for some experiments too. No solution was really convincing, rather worse than the status quo. So for the time being, I will leave it as is.
