### ISSUE TITLE
Allow choosing a CSS class

### ISSUE THREAD

**Issue by cebola2** [akilli/ckeditor4-detail#3]
This a feature request: allow choosing a CSS class for details. I have been unable to retain different CSS classes for details elements except by editing the source. On editing again CKEditor wipes out the CSS class. My attempts at allowing class='*' on the code by changing CKEditor configurations have failed so far.

Example pages: https://cdi1tp.math.tecnico.ulisboa.pt/praticas/1 (click both "Sugestões..." and "Soluções".

**Comment by akilli** [comment]
These are actually to requests:

1. Preserve existing CSS classes (or maybe even more generic: existing attributes)
2. Allow choosing CSS classes

Concerning 1.:
Currently this widget deliberately [removes all attributes of the details-element in the downcast method](https://github.com/akilli/ckeditor4-detail/blob/master/plugin.js#L55), therefore your attempts failed. The removing is actually not necessary at all, so I could change the downcast method.

Concerning 2.:
I do not want to introduce a dialog just for setting an optional CSS class. But I could think of integrating with the [Styles Combo plugin](https://ckeditor.com/cke4/addon/stylescombo) as described [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_styles.html#widget-styles)

**Comment by cebola2** [comment]
Thanks for the explanations. I have adapted the local version and 1.works perfectly.

**Comment by akilli** [comment]
@cebola2 

In case you just removed that line linked in 1. and have plans to work with nested instances of this widget, some CKEditor-internal attributes might remain on save or when toggling between source code- and rich text-mode. Just keep that in mind.

**Comment by cebola2** [comment]
Thanks, I'll keep that in mind. I have no plans for nested details. I immediately noticed that I needed to close opened instances.
